
# A list of the files that will be required
files = [
  'lexer', # The lexer => takes a chunk of code and returns a list of tokens
  'nodes', # The nodes => All nodes part of the AST
  'parser.tab', # the compiled parser, this file is automatically generated, do not edit
  'reader',
  'sender',
  'runtime'# this class is what actually takes a twisp program and runs it
]

# require all the files mentioned above
files.each do |file|
  require "twirlio/#{file}"
end
